### ISSUE TITLE
Text Component does not announce "disabled" #30937

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/react-native-notes#1]
https://github.com/facebook/react-native/issues/30937

**Comment by fabriziobertoglio1987** [comment]
Test Cases

2. TouchableNativeFeedback

```jsx
<TouchableNativeFeedback
  accessibilityRole="button"
  disabled
  accessibilityState={{disabled: true}}>
  <View>
    <Text>TouchableNativeFeedback</Text>
  </View>
</TouchableNativeFeedback>
```

**Expected Result**:
- 
- 

**Actual Result**:

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
Test Cases

1. ScreenReader does **NOT** announce disabled when moving focus to TouchableNativeFeedback

```jsx
<TouchableNativeFeedback
  accessibilityRole="button"
  disabled
  accessibilityState={{disabled: true}}>
    <Text>TouchableNativeFeedback</Text>
</TouchableNativeFeedback>
```

**Expected Result**:
- ScreenReader announces disabled

**Actual Result**:
- ScreenReader does **NOT** announce disabled

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="https://user-images.githubusercontent.com/24992535/152468427-cfac696f-1c1b-4f18-8099-986e8913cedf.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

2. ScreenReader does announce disabled when moving focus to TouchableNativeFeedback

```jsx
<TouchableNativeFeedback accessibilityState={{disabled: true}}>
    <View>
       <Text>TouchableNativeFeedback</Text>
    </View>
</TouchableNativeFeedback>
```

**Expected/Actual Result**:
- ScreenReader announces disabled

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="https://user-images.githubusercontent.com/24992535/152468902-6d37f18a-6088-467b-9f04-fe5adc77b970.mp4" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
Test Cases

3. ScreenReader announces disabled when moving focus on `<View focusable={true} />`

```jsx
<View
  focusable={true}
  style={{backgroundColor: 'red', height: 100, width: 100}}
  accessibilityState={{disabled: true}}>
  <Text style={{backgroundColor: 'green', color: 'white'}}>
    This is a View and it has an accessibilityState
  </Text>
</View>
```

**Expected Result**:
- 

**Actual Result**:
- 


**<details><summary>NOTES:</summary>**
<p>

<details><summary>Note number 1</summary>
<p>

</p>
</details>

</p>
</details>

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
Test Cases

4. ScreenReader announces disabled when moving focus to Text

```jsx
<TouchableNativeFeedback accessibilityState={{disabled: true}}>
    <Text>TouchableNativeFeedback</Text>
</TouchableNativeFeedback>
```

Adding the prop `accessible` to `ReactTextAnchorViewManager` fixes the problem for this component. 
The same solution from my previous pr https://github.com/facebook/react-native/issues/30935#issuecomment-808412263.

https://github.com/fabriziobertoglio1987/react-native-notes/blob/9cd43340a7e2443564c2ff5e8e85d37f6e1e47ef/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java#L38-L39

```java
  @ReactProp(name = "accessible")
  public void setAccessible(ReactTextView view, boolean accessible) {
    view.setFocusable(accessible);
  }
```

**Expected/Actual Result**:
- ScreenReader announces disabled

**TO-DO**:
- [ ] Consider adding the prop to shared parent class to fix this issue for all components

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="https://user-images.githubusercontent.com/24992535/152476788-6bd51cf4-1bcf-423b-a37a-90d3271c0c26.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
**TO-DO**:
- [x] Review diff
- [x] Write a list of edge cases
- [x] Test edge cases
- [x] Fix PR to handle edge case
- [ ] Review fix
- [ ] Test
- [ ] Write test cases

**Fix PR to handle edge case**:

- [ ] Remove Java logic (setAccessible) method in TextAnchorManager
- [ ] pass prop disabled to `NativeText`
- [ ] change prop as previously done with button
- [ ] test

**Edge Cases**
- [ ] onPress and onLongPress 
      accessibilityState.disabled does not disable Text https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033321965
      Consider adding test case to re-open [issue#30947](https://github.com/facebook/react-native/issues/30947)
- [ ] accessibilityLabel, Role and Actions

**Low Priority**
- [ ] Consider adding the prop to shared parent class to fix this issue for all components
- [ ] Further investigate issue and find the real problem that causes TextManager to not have prop accessible while View has it
- [ ] Evaluate over-riding the prop in TextAnchorViewManager
- [ ] ~~Nested Text ==> [not accessible with ReactNative](https://github.com/facebook/react-native/issues/32004)~~
- [ ] ~~[ReactViewManager#accessible][10]~~
      I'm adding [setAccessible](https://github.com/fabriziobertoglio1987/react-native/blob/c263d93bf766f9182143058ea56f9e2adb4c33e2/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java#L56) prop and not [setFocusable](https://github.com/fabriziobertoglio1987/react-native/blob/c263d93bf766f9182143058ea56f9e2adb4c33e2/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java#L237) ==> not relevant

[10]: https://github.com/fabriziobertoglio1987/react-native-notes/blob/9cd43340a7e2443564c2ff5e8e85d37f6e1e47ef/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java#L240-L253

**Comment by fabOnReact** [comment]
Test Cases

5. ScreenReader announces disabled when moving focus TextInput Component

```jsx
<>
  <Text>This Component is not disabled</Text>
  <TextInput
    placeholder="This component is disabled"
    accessibilityState={{disabled: true}}
  />
</>
```

**Expected/Actual Result**:
- ScreenReader announces disabled

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

<video src="https://user-images.githubusercontent.com/24992535/152706833-4bdba8a7-62ac-4573-9853-5ff1efd37ef2.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

7.6. Text has `onPress` callback and `accessibilityState = {{ disabled: true }}`

```javascript
<Text
  onPress={() => console.warn('onPress')}
  accessibilityState={{disabled: true}}>
  Awesome App
</Text>
```

**Expected Result**:
The Text is `disabled` and should **NOT** trigger the `onPress` callback

**Actual Result**:
The Text announces **disabled**, but is not **disabled** and **triggers** the `onPress` callback

Related https://github.com/facebook/react-native/issues/30947 Fixed with commits https://github.com/facebook/react-native/pull/33076/commits/6ab7ab34e56411a7e87f396feb2f7ece1c4f98dd https://github.com/fabriziobertoglio1987/react-native/commit/17095c6615107695f44af262846da446868b4cd8

<details><summary>CLICK TO OPEN TESTS RESULTS - ON PR BRANCH BEFORE COMMIT 1c4f98dd</summary>
<p>

On PR Branch before commit [1c4f98dd][1] the user is allowed to click on the text and trigger the `onPress` callback.

<video src="https://user-images.githubusercontent.com/24992535/153119695-cf1d9268-1bf3-4f7a-ab68-1643a928a0cd.mp4" width="1000" />

</p>
</details>

<details><summary>CLICK TO OPEN TESTS RESULTS - MAIN BRANCH</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153120953-dc20b1e9-d3a9-450b-adc0-2da07eeaacb2.mp4" width="1000" />

</p>
</details>

[1]: https://github.com/facebook/react-native/pull/33076/commits/6ab7ab34e56411a7e87f396feb2f7ece1c4f98dd

**Comment by fabOnReact** [comment]
https://user-images.githubusercontent.com/24992535/153145503-220619c3-4008-485d-9295-e0b623a856fc.mp4


https://user-images.githubusercontent.com/24992535/153145525-80b6a10b-c1b3-44bc-9056-9b8f6cd533f9.mp4


https://user-images.githubusercontent.com/24992535/153145535-29aeaedc-f7d2-4471-b756-2b5765a7f8ea.mp4


https://user-images.githubusercontent.com/24992535/153145546-2b945cef-20e5-47cd-b402-4bde941376b2.mp4


https://user-images.githubusercontent.com/24992535/153145556-9f2d9f33-1adc-4806-8b24-cbb6c4abab75.mp4


https://user-images.githubusercontent.com/24992535/153145560-71dc56d2-f418-467d-98ca-6b51c2c43e69.mp4


https://user-images.githubusercontent.com/24992535/153145570-8c2491ca-74ea-48cd-8a22-87a2655d80ac.mp4


https://user-images.githubusercontent.com/24992535/153145576-25d706e5-31b6-4545-b969-3f20f7c48f8e.mp4

**Comment by fabOnReact** [comment]
Test Cases

1. Text has `disabled` and `accessibilityState={{disabled: false}}`

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  disabled
  accessibilityState={{disabled: false}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected/Actual Result**:
The ScreenReader should announce `disabled` when the focus moves to the `Text`.
The onPress handler is disabled.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153152102-47ee29e8-49f0-4722-af75-a12359f278ed.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

2. Text has `disabled`

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  disabled>
  This is a Text
</Text>
```


</p>
</details>


**Expected/Actual Result**:
- The Text is disabled
- The ScreenReader announces `disabled`.
- The onPress handler is disabled.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145525-80b6a10b-c1b3-44bc-9056-9b8f6cd533f9.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

3. Text has `accessibilityState={{disabled: true}}`

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected/Actual Result**:
- The ScreenReader announces `disabled` when the focus moves to the `Text`.
- The `Text` is **disabled**. Users are **NOT** allowed to interact with the text.
- The onPress handler is disabled.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145535-29aeaedc-f7d2-4471-b756-2b5765a7f8ea.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

4. Text has `accessibilityState={{disabled:false}}`

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  accessibilityState={{disabled: false}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected/Actual Result**:
- The ScreenReader does **not** announce `disabled`.
- The `Text` is not **disabled**. Users are allowed to interact with the text.
- The onPress handler is **NOT** disabled.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145546-2b945cef-20e5-47cd-b402-4bde941376b2.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

5. Text has `disabled={false}` `accessibilityState={{disabled:true}}`

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  disabled={false}
  accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected/Actual Result**:
The Text is **not** disabled. 

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145556-9f2d9f33-1adc-4806-8b24-cbb6c4abab75.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

7.1 Text has `disabled` set to true and `accessibilityState={{disabled: false}}`  (main branch)

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  disabled
  accessibilityState={{disabled: false}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected Result**:
The ScreenReader should announce `disabled` when the focus moves to the `Text`.

**Actual Result**:
The ScreenReader does not announce `disabled` when the focus moves to the `Text`.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145560-71dc56d2-f418-467d-98ca-6b51c2c43e69.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

7.3. Text has `accessibilityState={{disabled: true}}` (tested on **main** branch).

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected Result**:
- The ScreenReader announces `disabled` when the focus moves to the `Text`.
- The `Text` is **disabled**. Users are **NOT** allowed to interact with the Text (click and trigger onPress callback).

**Actual Result**:
- The `Text` is **NOT disabled**. 
- Users **are allowed** to interact with the Text.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145570-8c2491ca-74ea-48cd-8a22-87a2655d80ac.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

7.5 Text has `disabled={false}` and `accessibilityState={{disabled:true}}` (on main branch)

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text
  style={styles.text}
  onPress={() => console.warn('onPress')}
  disabled={false}
  accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected Result**:
The Text is disabled. ScreenReader should announce `disabled` when the focus moves to the `Text`.

**Actual Result**:
- The ScreenReader does not announce `disabled`.
- Users are allowed to interact with the Text.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153145576-25d706e5-31b6-4545-b969-3f20f7c48f8e.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
## Summary



This issue fixes https://github.com/facebook/react-native/issues/30937 https://github.com/facebook/react-native/issues/30947 ([Test Case 7.1][7.1], [Test Case 7.3][7.3], [Test Case 7.5][7.5]) .
The issue is caused by:

1) the missing prop `accessibilityState` in the Text component https://github.com/fabriziobertoglio1987/react-native/commit/6ab7ab34e56411a7e87f396feb2f7ece1c4f98dd
2) missing setter for prop `accessible` in `ReactTextAnchorViewManager` https://github.com/fabriziobertoglio1987/react-native/commit/17095c6615107695f44af262846da446868b4cd8

Related PRs https://github.com/facebook/react-native/pull/33070 https://github.com/callstack/react-native-slider/pull/354

## Changelog



[General] [Fixed] - Text Component does not announce and disable click functionality when disabled

## Test Plan



[1]. Text has `disabled` and `accessibilityState={{disabled: false}}`
[2]. Text has `disabled`
[3]. Text has `accessibilityState={{disabled: true}}`
[4]. Text has `accessibilityState={{disabled:false}}`
[5]. Text has `disabled={false}`  and `accessibilityState={{disabled:true}}`
7. Test Cases on the main branch
[7.1]. Text has `disabled` and `accessibilityState={{disabled: false}}`
[7.3] Text has `accessibilityState={{disabled: true}}`
[7.5] Text has `disabled={false}`  and `accessibilityState={{disabled:true}}`

[1]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465424
[2]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465631
[3]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465706
[4]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465755
[5]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465813
[7.1]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465874
[7.3]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033465961
[7.5]: https://github.com/fabriziobertoglio1987/react-native-notes/issues/1#issuecomment-1033466018

**Comment by fabOnReact** [comment]
PR https://github.com/facebook/react-native/pull/33076

**Comment by fabOnReact** [comment]
Test Cases

7.7 Text has `accessibilityState={{disabled:true}}` and no method `setAccessible` in `ReactTextAnchorViewManager` (tested on commit https://github.com/facebook/react-native/pull/33076/commits/6ab7ab34e56411a7e87f396feb2f7ece1c4f98dd)

Without the below logic in ReactTextAnchorViewManager (added in commit https://github.com/facebook/react-native/commit/17095c6615107695f44af262846da446868b4cd8).

```java
  @ReactProp(name = "accessible")
  public void setAccessible(ReactTextView view, boolean accessible) {
    view.setFocusable(accessible);
  }
```

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected Result**:
The ScreenReader announces `disabled` when the focus moves to the `Text`.

**Actual Result**:
- The ScreenReader does not announce `disabled`.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153779729-44cdea09-58a0-430a-9b94-e3dd19ed2e57.mp4" width="1000" />

</p>
</details>

**Comment by fabOnReact** [comment]
Test Cases

6. Text has `accessibilityState={{disabled:true}}` and method `setAccessible` in `ReactTextAnchorViewManager` (tested on commit https://github.com/facebook/react-native/pull/33076/commits/17095c6615107695f44af262846da446868b4cd8)

With the below logic in ReactTextAnchorViewManager.

```java
  @ReactProp(name = "accessible")
  public void setAccessible(ReactTextView view, boolean accessible) {
    view.setFocusable(accessible);
  }
```

<details><summary>CLICK TO OPEN SOURCECODE</summary>
<p>

```javascript
<Text accessibilityState={{disabled: true}}>
  This is a Text
</Text>
```

</p>
</details>

**Expected/Actual Result**:
The ScreenReader announces `disabled` when the focus moves to the `Text`.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/153780083-cd0df5dd-54c8-45ea-ade3-fc481620f47a.mp4" width="1000" />

</p>
</details>
