### ISSUE TITLE
error: add_cacheinfo failed to refresh for path 'packages/react-native-gradle-plugin/gradlew.bat'; merge aborting.

### ISSUE THREAD

**Issue by fabOnReact** [fabriziobertoglio1987/react-native-notes#8]
### ISSUE

Merge main in old branch causes the following error

```bash
error: add_cacheinfo failed to refresh for path 'packages/react-native-gradle-plugin/gradlew.bat'; merge aborting.
```

<details><summary>Full Log</summary>
<p>

![image](https://user-images.githubusercontent.com/24992535/154604740-7edbc154-a802-402e-ad19-27781f4d9738.png)

</p>
</details>

### Current Investigation

- Reproduces both macos and ubuntu
- Reproduces on new clone (it is not caused by my fork)
- Maybe it's caused by the github commit changing the `.gitattributes`. https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b
- I deleted all .gitconfig settings on macos

### Links
Stackoverflow explanation https://stackoverflow.com/a/57199694
PRs https://github.com/facebook/react-native/pull/12800 https://github.com/facebook/react-native/pull/31398 https://github.com/facebook/react-native/pull/31128 https://github.com/facebook/react-native/pull/32160 https://github.com/helium/hotspot-app/pull/944

**Comment by fabOnReact** [comment]
### TODO

- [x] move main to parent of https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b
- [x] run command `g merge main`
- [x] move main to https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b
- [x] run command `g merge main`
- [ ] merge next commit
- [ ] read discussion in https://github.com/facebook/react-native/pull/12800 https://github.com/facebook/react-native/pull/31398 https://github.com/facebook/react-native/pull/31128 https://github.com/facebook/react-native/pull/32178
- [ ] read https://stackoverflow.com/a/57199694
- [ ] check again your git settings

**Comment by fabOnReact** [comment]
I think the problem could be:
- the history
- collaborating on branches used by developers that have different machine. For ex. Windows changes line endings of gradlew.bat, when you check out that branch you trigger issues with git

When git runs a merge:
- it goes through each commit 
- then run commands to merge/rebase for that commit
- git reaches the commit https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b 
- the commit adds a .gitattributes settings to change line endings
- the settings in .gitattributes cause git to change the line endings of some files (adding `^K` to the end of `gradlew.bat` when you run any command)
- on some machines/branches (for me both linux and macos) causes error when merging
- when merges the next commit. The error is triggered

```
error: add_cacheinfo failed to refresh for path 'packages/react-native-gradle-plugin/gradlew.bat'; merge aborting.
```
- I was able to prove this in the past, by rebase branches with head before https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b 
- I could not rebase them on the master after  that commit 
- But I was able to rebase them to the commit before, then rebase them to the new main with head after that specific commit 

The issue is caused by trying to rebase a branch or using a main branch for rebase that includes that .gitattributes.

**Comment by fabOnReact** [comment]
https://github.com/facebook/react-native/pull/31128#issuecomment-825986802

>If you want to see how these files are actually stored:
>Remove .gitattributes (so that no conversion happens)

I solved the problem with the following steps:

1) checkout branch I want to rebase
2) the branch was already rebased and included commit https://github.com/facebook/react-native/commit/73844712b6283dcc41805129cc8da305d5490c0b which brought `.gitattributes` file in the branch
    The file below triggers the error `error: add_cacheinfo failed to refresh for path 'packages/react-native-gradle-plugin/gradlew.bat'; merge aborting.` when running `git merge master`. 
```
-# Windows files should use crlf line endings
-# https://help.github.com/articles/dealing-with-line-endings/
-*.bat text eol=crlf
```
3) I remove the  `.gitattributes` files from the branch.
4) `git` stops converting the line ending
5) I merge main branch. `.gitattributes` files was already removed from main branch with https://github.com/facebook/react-native/pull/31398/files. Git runs the merge without problems. Also no diff because the file already deleted from main.
